### ISSUE TITLE
export workspace member crates?

### ISSUE THREAD

**Issue by evanrichter** [TheNeikos/crane-workspaces#5]
Would it be possible to `buildWorkspace {}` but then have access to individual member crate (bin/lib) outputs?

My usecase is wanting to build the entire workspace (with better-than-default rebuild detection) but then I have some integration tests that only need one crate's output.

```
1. Workspace crates
  - Crate A
  - Crate B        <--- change src/main.rs
2. Build Workspace <--- only rebuild Crate B
3. Integration tests
  - Crate A tests  <--- not run, inputs haven't changed
  - Crate B tests  <--- run test
```

**Comment by TheNeikos** [comment]
Yep! This is currently possible:

https://github.com/TheNeikos/crane-workspaces/blob/40628de7db4e95351f84417f6c3988c8166ff2ae/lib/buildWorkspace.nix#L225-L228

We are passing thru the `workspaceMembers`. So you should be able to call `(buildWorkspace { }).workspaceMembers.crateA` and it will only build that crate.

**Comment by evanrichter** [comment]
thanks for showing me the passthroughs! that's a great concept that I could probably find a lot of uses for besides here, too.

I do think it's passing through the wrong binding though, since `workspaceMembers` is rebound in a nested `let-in`: #6

**Comment by TheNeikos** [comment]
🤦‍♀️ Woops, that passthru was there before I refactored that part :)

Good catch!
